Rohan/2 search pane course catalog
GTBitsOfGood/gt-scheduler-website pull request #14
Opened 2022-02-25 05:04 UTC by luke9kim8

## PR Title/Tagline

Issue Number(s): #2 

What does this PR change and why?
Add the draft UI of course search in "Course Search" tab (2nd column)

<img width="800" alt="image" src="https://user-images.githubusercontent.com/39681900/155656353-bf326c85-5f3f-4b16-8200-2aafc1914ba3.png">

### Checklist

- [x]  Database schema docs have been updated or are not necessary
- [x]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [x]  Tests have been written and executed or are not necessary
- [x]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [x]  Github issues have been linked in relevant commits
- [x]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### Critical Changes

- No critical changes

### Related PRs

- No related PRs

### How to Test

- `yarn start`
- navigate to "Course Search Tab"
- Check if the query div (2nd column) matches as described in [Figma](https://www.figma.com/file/CkystexX4qQO9OnZRxktXa/GT-Scheduler-%2F-Spr21?node-id=18%3A2)
- Check if it works on mobile view, which it should
- Double check if the 2nd column in the "Schedule" tab is working fine, bc we thought we were replacing that column with our new column

2022-02-26 00:07 UTC, kphan32 requested changes
Some small things, also:
1. Linting warnings (resolve these pls)
2. Can you make it so that selected buttons do not change size?

2022-02-26 00:07 UTC, kavinphan commented on src/components/CourseFilter/index.tsx
> +/* eslint-disable react/self-closing-comp */
Can you leave a nolint doc, just a comment explaining why the linter is disabled here.

2022-02-26 00:07 UTC, kavinphan commented on src/components/SearchContainer/index.tsx
> +/* eslint-disable import/no-duplicates */
nolint doc here

2022-02-26 00:07 UTC, kavinphan commented on src/components/SearchContainer/index.tsx
> +// }
What is this

2022-02-26 22:26 UTC, rohkash commented on src/components/CourseFilter/index.tsx
> +/* eslint-disable react/self-closing-comp */
I ended up deleting this, it was left over when I was trying to test different things and wanted to avoid errors.

2022-02-26 22:26 UTC, rohkash commented on src/components/SearchContainer/index.tsx
> +/* eslint-disable import/no-duplicates */
I ended up deleting this, it was left over when I was trying to test different things and wanted to avoid errors.

2022-02-26 22:26 UTC, rohkash commented on src/components/SearchContainer/index.tsx
> +// }
I ended up deleting this, it was left over when I was trying to test different things and wanted to avoid errors.

2022-03-01 06:03 UTC, kphan32 approved these changes
lgtm :+1:

2022-03-01 06:04 UTC, merged